name: Build

on:
  push:
    branches:
      - main
  workflow_dispatch: # 手動実行を有効化

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    with:
      board: ${{ github.event.inputs.board }}
      shield: ${{ github.event.inputs.shield }}
      target: ${{ github.event.inputs.target }}
      ref: ${{ github.event.inputs.ref }}
      archive-name: ${{ github.event.inputs.archive_name }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
