name: Build

on:
  workflow_dispatch: # 手動実行を許可

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    with:
      board: nice_nano_v2
      shield: crosses
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
